<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>CleanArchitecture.Graph</RootNamespace>
    <AssemblyName>CleanArchitecture.Graph</AssemblyName>
    <UserSecretsId>4c53e5a0-6a3a-4bfb-9ac0-385c169e26e7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Graph.Schema\Graph.Schema.csproj" />
    <ProjectReference Include="..\Graph.DataLoaders\Graph.DataLoaders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

</Project>
