<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CleanArchitecture.Graph.SchemaTests</RootNamespace>
    <AssemblyName>CleanArchitecture.Graph.SchemaTests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="CookieCrumble" />
    <PackageReference Include="CookieCrumble.HotChocolate" />
    <PackageReference Include="CookieCrumble.Xunit3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Pampa.CookieCrumble.Spec" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Graph.Schema\Graph.Schema.csproj" />
    <ProjectReference Include="..\..\src\Graph.DataLoaders\Graph.DataLoaders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
